synchrotron:compile:
  stage: compile
  extends: .compile_benchmark
  script:
    - compile_analyses.py synchrotron

synchrotron:process:
  stage: process
  extends: .phy_benchmark
  tags:
    - s3
  needs: ["common:detector", "synchrotron:compile"]
  script:
    - bash benchmarks/synchrotron/synchrotron.sh --all

synchrotron:results:
  stage: collect
  needs: ["synchrotron:process"]
  script:
    - ls -lrth
