tcs:compile:
  stage: compile
  extends: .compile_benchmark
  script:
    - compile_analyses.py tcs

tcs:simulate:
  stage: simulate
  extends: .phy_benchmark
  tags:
    - phy
  needs: ["common:detector", "tcs:compile"]
  parallel:
    matrix:
      - EBEAM: 5
        PBEAM: 41
        TAG: s450
      - EBEAM: 10
        PBEAM: 100
        TAG: s100
      - EBEAM: 18
        PBEAM: 275
        TAG: s800
  script:
    #- bash benchmarks/tcs/tcs.sh --all --ebeam ${EBEAM} --pbeam ${PBEAM} --tag ${TAG}
    - bash benchmarks/tcs/tcs.sh --data-init --sim --rec --ebeam ${EBEAM} --pbeam ${PBEAM} --tag ${TAG}

tcs:results:
  stage: collect
  needs: ["tcs:simulate"]
  script:
    - ls -lrth
