single:compile:
  extends: .compile_benchmark
  stage: compile
  script:
    - compile_analyses.py single

single:simulate:
  extends: .phy_benchmark
  timeout: 2 hours
  stage: simulate
  needs: ["common:detector"]
  script:
    - bash benchmarks/single/simulate.sh e-_1GeV_45to135deg

single:reconstruct:
  extends: .phy_benchmark
  timeout: 2 hours
  stage: reconstruct
  needs: ["single:simulate"]
  script:
    - bash benchmarks/single/reconstruct.sh e-_1GeV_45to135deg

single:analyze:
  extends: .phy_benchmark
  timeout: 2 hours
  stage: analyze
  needs: ["single:reconstruct", "single:compile"]
  script:
    - bash benchmarks/single/analyze.sh e-_1GeV_45to135deg

single:results:
  stage: collect
  needs: ["single:analyze"]
  script:
    - ls -al
