dvcs:compile:
  stage: compile
  extends: .compile_benchmark
  script:
    - compile_analyses.py dvcs

dvcs:process:
  stage: process
  extends: .phy_benchmark
  tags:
    - phy
  needs: ["common:detector", "dvcs:compile"]
  script:
    #- bash benchmarks/dvcs/dvcs.sh --all
    - bash benchmarks/dvcs/dvcs.sh --data-init --sim --rec

dvcs:results:
  stage: collect
  needs: ["dvcs:process"]
  script:
    - ls -lrth
      #pip install junitparser
      #- python dvcs/scripts/merge_results.py
